/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import models.Room;
import models.RoomDao;
import models.Utils;

/**
 *
 * @author idra1
 */
public class addRoomView extends javax.swing.JFrame {

    /**
     * Creates new form addRoomView
     */
    private final RoomDao rooms;
    private final AdminRoomsView arv;
    private int editRoomId = -1;
    private Room actualRoom;

    public addRoomView(RoomDao rooms, AdminRoomsView arv) { //Constructor de agregado
        initComponents();
        this.rooms = rooms;
        this.arv = arv;
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addRoomButton.addActionListener(e -> addRoomActionPerformed());
        addWindowClosingEvent();
        Utils.centerWindow(this);

    }

    public addRoomView(RoomDao rooms, AdminRoomsView arv, Room actualRoom) { //Constructor de edicion
        initComponents();
        this.rooms = rooms;
        this.arv = arv;
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addRoomButton.setText("Aplicar");
        newRoomNumberTxt.setText(String.valueOf(actualRoom.getRoomNumber()));
        newRoomNumberTxt.setEnabled(false);
        newRoomCategoryCombo.setSelectedItem(actualRoom.getCategory());
        newRoomPriceTxt.setText(String.valueOf(actualRoom.getPrice()));
        editRoomId = actualRoom.getID();
        this.actualRoom = actualRoom;
        addRoomButton.addActionListener(e -> editRoomActionPerformed());
        addWindowClosingEvent();
        Utils.centerWindow(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addRoomButton = new javax.swing.JButton();
        newRoomPriceTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newRoomNumberTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        newRoomCategoryCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Room Add");
        setResizable(false);

        addRoomButton.setText("Añadir ");

        jLabel3.setText("Precio");

        jLabel2.setText("Categoría");

        jLabel1.setText("Número");

        newRoomCategoryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Superior", "Suite" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(newRoomPriceTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                        .addComponent(newRoomNumberTxt, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(newRoomCategoryCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 93, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel2))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addRoomButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newRoomNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newRoomCategoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newRoomPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addRoomButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRoomActionPerformed() {
        if (newRoomNumberTxt.getText().isBlank() || newRoomPriceTxt.getText().isBlank()) {
            Utils.ShowInfo("Complete todos los campos");
            return;
        }
        double price;
        int roomNum;
        try {
            price = Double.parseDouble(newRoomPriceTxt.getText());
            roomNum = Integer.parseInt(newRoomNumberTxt.getText());
        } catch (NumberFormatException ex) {
            Utils.ShowErr("Los campos deben ser numericos", "Excepcion");
            return;
        }
        if (rooms.getAll().stream().anyMatch(r -> r.getRoomNumber() == roomNum)) {
            Utils.ShowInfo("Ya existe una habitacion con el número " + roomNum);
            return;
        }

        Room r = new Room(-1, newRoomCategoryCombo.getSelectedItem().toString(), price, roomNum);
        rooms.save(r);
        arv.addRoom(r);
        arv.setEnabled(true);
        this.dispose();
    }

    private void editRoomActionPerformed() {
        if (newRoomNumberTxt.getText().isBlank() || newRoomPriceTxt.getText().isBlank()) {
            Utils.ShowInfo("Complete todos los campos");
            return;
        }
        double price;
        int roomNum;
        try {
            price = Double.parseDouble(newRoomPriceTxt.getText());
            roomNum = Integer.parseInt(newRoomNumberTxt.getText());
        } catch (NumberFormatException ex) {
            Utils.ShowErr("Los campos deben ser numericos", "Excepcion");
            return;
        }
        if (rooms.getAll().stream().anyMatch(r -> r.getRoomNumber() == roomNum) && roomNum != actualRoom.getRoomNumber()) {
            Utils.ShowInfo("Ya existe una habitacion con el número " + roomNum);
            return;
        }
        Room newRoom = new Room(editRoomId,newRoomCategoryCombo.getSelectedItem().toString(),price,roomNum);
        rooms.update(actualRoom, newRoom);
        arv.loadRooms();
        
        arv.setEnabled(true);
        this.dispose();
    }

    private void addWindowClosingEvent() {
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                arv.setEnabled(true);
                dispose();

            }
        });
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoomButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> newRoomCategoryCombo;
    private javax.swing.JTextField newRoomNumberTxt;
    private javax.swing.JTextField newRoomPriceTxt;
    // End of variables declaration//GEN-END:variables
}
